#!/usr/bin/env bash
# Regenerate internal/oui/oui.txt (the full IEEE OUI registry, embedded at build
# time — see internal/oui/oui.go).
#
# Safe to run on every build: the IEEE CSV is cached and only re-fetched when
# stale (or forced), and a fetch failure falls back to the cache or the existing
# table so an offline build still succeeds.
#
# Usage: scripts/update-oui.sh [--force]
#   PUCKVIEW_OUI_MAX_AGE_DAYS  re-fetch cadence (default 30)
set -euo pipefail

cd "$(dirname "$0")/.."
OUT="internal/oui/oui.txt"
CACHE="internal/oui/.oui-cache.csv"
SRC="https://standards-oui.ieee.org/oui/oui.csv"
MAX_AGE_DAYS="${PUCKVIEW_OUI_MAX_AGE_DAYS:-30}"

force=false
[[ "${1:-}" == "--force" ]] && force=true

# Decide whether to hit the network: only if forced, or the cache is missing or
# older than MAX_AGE_DAYS.
need_fetch=true
if [[ "$force" == false && -f "$CACHE" ]] && find "$CACHE" -mtime "-${MAX_AGE_DAYS}" -print -quit | grep -q .; then
  need_fetch=false
  echo "using cached $CACHE (< ${MAX_AGE_DAYS}d old)"
fi

if [[ "$need_fetch" == true ]]; then
  echo "fetching $SRC ..."
  tmp="$(mktemp)"
  if curl -fsSL --max-time 180 "$SRC" -o "$tmp" && [[ -s "$tmp" ]]; then
    mv "$tmp" "$CACHE"
  else
    rm -f "$tmp"
    echo "warning: OUI fetch failed" >&2
    if [[ -f "$CACHE" ]]; then
      echo "  -> using stale cache $CACHE" >&2
    elif [[ -f "$OUT" ]]; then
      echo "  -> no cache; keeping existing $OUT" >&2
      exit 0
    else
      echo "error: no OUI data (no network, no cache, no table)" >&2
      exit 1
    fi
  fi
fi

# Deterministic transform of the cached CSV -> "PREFIX<TAB>Vendor", sorted.
# IEEE CSV columns: Registry,Assignment,Organization Name,Organization Address.
{
  echo "# puckview embedded OUI table — generated by scripts/update-oui.sh from"
  echo "# $SRC"
  echo "# Full IEEE registry; embedded at build time (see internal/oui/oui.go)."
  awk -F',' 'NR>1 && $2 ~ /^[0-9A-Fa-f]{6}$/ {
    name=$3
    gsub(/^"|"$/, "", name)
    gsub(/\r/, "", name)
    if (name != "") printf "%s\t%s\n", toupper($2), name
  }' "$CACHE" | sort -u
} > "$OUT"

echo "wrote $(wc -l < "$OUT") lines to $OUT"
