// Package oui maps a MAC's 24-bit prefix to a vendor name using the full IEEE
// OUI registry, embedded at build time. There is no runtime refresh: vendor
// lookup is best-effort (randomized MACs have no vendor) and registered prefixes
// stay valid for years, so a snapshot degrades gracefully to "unknown". The
// table (oui.txt) is regenerated by the build pipeline (scripts/update-oui.sh).
package oui

import (
	"bufio"
	"bytes"
	"strconv"
	"strings"
	"sync"

	_ "embed"
)

//go:embed oui.txt
var raw []byte

var (
	once  sync.Once
	table map[string]string
)

func load() {
	table = make(map[string]string, 40000)
	sc := bufio.NewScanner(bytes.NewReader(raw))
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		// Format: "AABBCC<whitespace>Vendor Name"
		i := strings.IndexAny(line, " \t")
		if i < 6 {
			continue
		}
		prefix := strings.ToUpper(strings.ReplaceAll(line[:i], ":", ""))
		if len(prefix) != 6 {
			continue
		}
		table[prefix] = strings.TrimSpace(line[i+1:])
	}
}

// Lookup returns the vendor for a MAC, "(randomized)" for a locally-administered
// address, or "" when the prefix is not in the table.
func Lookup(mac string) string {
	once.Do(load)
	hex := strings.ToUpper(strings.NewReplacer(":", "", "-", "").Replace(strings.TrimSpace(mac)))
	if len(hex) < 6 {
		return ""
	}
	if isLocallyAdministered(hex) {
		return "(randomized)"
	}
	return table[hex[:6]]
}

// isLocallyAdministered checks bit 1 of the first octet (the U/L bit). Such
// addresses are randomized/virtual and carry no manufacturer identity. hex is
// the colon-stripped MAC; callers guarantee at least 6 chars.
func isLocallyAdministered(hex string) bool {
	b, _ := strconv.ParseUint(hex[:2], 16, 8)
	return b&0x02 != 0
}
